databases:
  - name: task-manager
    plan: free
    databaseName: task-manager
    user: postgres

services:
  - type: web
    plan: free
    name: task_manager
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn task_manager.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
